#!/usr/bin/env bash
# Install and configure HAproxy

apt-get -y update
apt-get -y install haproxy

echo -e '\nfrontend hordun-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend hordun-backend\n\nbackend hordun-backend\n\tbalance roundrobin\n\tserver 350079-web-01 54.175.122.179:80 check\n\tserver 350079-web-02 100.26.230.33:80 check\n' | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo systemctl restart haproxy
