#!/usr/bin/env bash
# Install and configure HAproxy

apt -y update
apt-get -y install haproxy

config=\
"frontend hordun-frontend
	bind *:80
	mode http
	default_backend hordun-backend

backend hordun-backend
	balance roundrobin
	server web-01 54.175.122.179:80 check
	server web-02 100.26.230.33:80 check
"

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
